<?php
include 'header.php';
?>

    <div class="print-header">
        <h1>TechSolutions Inc. Report</h1>
        <p>Generated by: @alex_admin | Date: <?php echo date("Y-m-d"); ?></p>
    </div>

    <div class="container">

        <div class="text-center" style="text-align: center; margin: 30px 0;">
            <h2 style="font-weight: 300; font-size: 2rem;">User List</h2>
            <p style="color: #666;">Create and manage user accounts.</p>
        </div>

        
        
        <div class="glass-panel form-section">
            <span class="section-title">New Company Add</span>
            <form>
                <div class="grid-layout desktop-4" style="grid-template-columns: 1fr 1fr;">
                  
                    <div><label>Name</label><input type="text" placeholder="Company Name" name="name" required></div>
                    <div><label>Address</label><input type="text" placeholder="Address" name="address"></div>
                    <div><label>Phone</label><input type="text" placeholder="Phone Number" name="phone"></div>
                    <div><label>Email</label><input type="email" placeholder="Email Address" name="email"></div>
                    <div><label>Website</label><input type="text" placeholder="Company Website" name="website"></div>
                    <div><label>Logo</label><input type="text" placeholder="Logo URL" name="logo"></div>
                </div>
                
                <div class="form-actions">
                    <button type="submit" name="add_company" class="btn btn-yellow"><i class="fa-solid fa-plus"></i> Add Company</button>
                </div>
                 
            </form>
        </div>

        

        <div class="glass-panel printable">
            <div style="display: flex; justify-content: space-between; margin-bottom: 15px;">
                <span class="section-title" style="margin:0;">All Company</span>
                <button onclick="window.print()" class="btn btn-dark" style="padding: 5px 15px; font-size: 0.8rem;"><i class="fa-solid fa-print"></i></button>
            </div>
            
            <div class="table-responsive">
                <table class="table-simple">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Name</th>
                            <th>Address</th>
                            <th>Phone</th>
                            <th>Email</th>
                            <th>Website</th>
                            <th>Logo</th>
                            <th style="text-align: right;">Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        $query = "SELECT * FROM companies";
                        $result = mysqli_query($conn, $query);

                        if (mysqli_num_rows($result) > 0) {
                            while ($row = mysqli_fetch_assoc($result)) {
                                echo "<tr><td>" . $row['id'] . "</td><td>" . $row['name'] . "</td><td>" . $row['address'] . "</td><td>" . $row['phone'] .
                                 "</td><td>" . $row['email'] . "</td><td>" . $row['website'] . "</td><td><img src='" . $row['logo'] .
                                  "' width='50' height='50'></td> <td style='text-align: right;'>
                                <i class='fa-solid fa-pen' style='color:var(--warning); margin-right: 10px; cursor: pointer;'></i>
                               
                            </td></tr>";
                            }
                        }
                        ?>
                    </tbody>
                </table>
            </div>
        </div>


        

        <div class="glass-panel form-section">
            <span class="section-title">New User Add</span>
            <form>
               <div class="desktop-span-2">
                      <div>
                        <label>Company</label>
                        <select name="company_id" id="company_id" required>
                            <option value="">Select Company</option>
                            <?php
                            $query = "SELECT id, name FROM companies";
                            $result = mysqli_query($conn, $query);

                            if (mysqli_num_rows($result) > 0) {
                                while ($row = mysqli_fetch_assoc($result)) {
                                    echo "<option value='" . $row['id'] . "'>" . $row['name'] . "</option>";
                                }
                            }
                            ?>
                        </select>
                    </div>
                </div>
                <div class="grid-layout desktop-4" style="grid-template-columns: 1fr 1fr;">
                  
                    <div><label>User Name</label><input type="text" placeholder="User Name" name="username" required></div>
                    <div><label>Password</label><input type="password" placeholder="Password" name="password" required></div>
                    <div><label>Role</label><input type="text" placeholder="Role" name="role"></div>
                  
                    <div>
                        <label>Status</label>
                        <select name="status">
                            <option value="active">Active</option>
                            <option value="inactive">Inactive</option>
                        </select>
                    </div>
                </div>
                
                
                <div class="form-actions">
                    <button type="submit" name="add_user" class="btn btn-yellow"><i class="fa-solid fa-plus"></i> Add User</button>
                </div>
                 
            </form>
        </div>

        

        <div class="glass-panel printable">
            <div style="display: flex; justify-content: space-between; margin-bottom: 15px;">
                <span class="section-title" style="margin:0;">All User</span>
                <button onclick="window.print()" class="btn btn-dark" style="padding: 5px 15px; font-size: 0.8rem;"><i class="fa-solid fa-print"></i></button>
            </div>
            
            <div class="table-responsive">
                <table class="table-simple">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>User Name</th>
                            <th>Company</th>
                            <th>Role</th>
                            <th>Status</th>
                            <th>Created At</th>
                      
                            <th style="text-align: right;">Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        $query = "SELECT * FROM users";
                        $result = mysqli_query($conn, $query);

                        if (mysqli_num_rows($result) > 0) {
                            while ($row = mysqli_fetch_assoc($result)) {
                                echo "<tr><td>" . $row['id'] . "</td><td>" . $row['username'] . "</td><td>" . $row['company_id'] . "</td><td>" . $row['role'] .
                                 "</td><td>" . $row['status'] . "</td><td>" . $row['created_at'] . "</td> <td style='text-align: right;'>
                                <i class='fa-solid fa-pen' style='color:var(--warning); margin-right: 10px; cursor: pointer;'></i>
                                
                            </td></tr>";
                            }
                        }
                        ?>
                    </tbody>
                </table>
            </div>
        </div>


                            


        

        

    </div>



<?php
include 'footer.php';
?>