<?php
include 'header.php';
?>
<?php
if ($_SERVER['REQUEST_METHOD'] == 'POST') {


    if (isset($_POST['add_user'])) {
        $username = $_POST['username'];
        $password = password_hash($_POST['password'], PASSWORD_BCRYPT);
        $role = $_POST['role'];
        $status = $_POST['status'];
        $company_id = $_POST['company_id'];
        $check_query = "SELECT id FROM users WHERE username='$username'";
        $check_result = mysqli_query($conn, $check_query);
        if (mysqli_num_rows($check_result) > 0) {
            echo "<script>alert('Username already exists'); window.location.href='users.php';</script>";
            exit();
        }

        $query = "INSERT INTO users (username, password, role, status, company_id) VALUES ('$username', '$password', '$role', '$status', '$company_id')";
        mysqli_query($conn, $query);
        header("Location: users.php");
        exit();
    }
    if (isset($_POST['update_user'])) {
        $user_id = $_GET['user_edit_id'];
        $username = $_POST['username'];
        $role = $_POST['role'];
        $status = $_POST['status'];
        $company_id = $_POST['company_id'];

        $check_query = "SELECT id FROM users WHERE username='$username' AND id != '$user_id'";
        $check_result = mysqli_query($conn, $check_query);
        if (mysqli_num_rows($check_result) > 0) {
            echo "<script>alert('Username already exists'); window.location.href='users.php';</script>";
            exit();
        }

        $update_fields = "username='$username', role='$role', status='$status', company_id='$company_id'";

        if (!empty($_POST['password'])) {
            $password = password_hash($_POST['password'], PASSWORD_BCRYPT);
            $update_fields .= ", password='$password'";
        }

        $query = "UPDATE users SET $update_fields WHERE id='$user_id'";
        mysqli_query($conn, $query);
        header("Location: users.php");
        exit();
    }

}
?>
    <div class="print-header">
           <h1><?php echo APP_NAME; ?> Report</h1>
        <p>Generated by: <?php echo $_SESSION['user_id'] . "@".$_SESSION['username']. " | Company: " . $_SESSION['company_id']; ?> | Date: <?php echo date("Y-m-d"); ?></p>

    </div>

    <div class="container">

        <div class="text-center" style="text-align: center; margin: 30px 0;">
            <h2 style="font-weight: 300; font-size: 2rem;">User List</h2>
            <p style="color: #666;">Create and manage user accounts.</p>
        </div>

        
        
        
        

       


        

        <div class="glass-panel form-section">
            <span class="section-title">New User Add</span>
            <form method="POST">


                <?php if (isset($_GET['user_edit_id'])) {
                    $user_edit_id = $_GET['user_edit_id'];
                    $query = "SELECT * FROM users WHERE id='$user_edit_id'";
                    $result = mysqli_query($conn, $query);
                    if (mysqli_num_rows($result) > 0) {
                        $user_data = mysqli_fetch_assoc($result);
                    }
                }
                ?>
                <div class="desktop-span-2">
                      <div>
                        <label>Company</label>
                        <input type="text" readonly placeholder="Company ID" name="company_id" value="<?php echo htmlspecialchars(isset($user_data['company_id']) ? $user_data['company_id'] : $_SESSION['company_id']); ?>" required>
                    </div>
                </div>
                <div class="grid-layout desktop-4" style="grid-template-columns: 1fr 1fr;">
                  
                    <div><label>User Name</label><input type="text" placeholder="User Name" name="username" value="<?php echo htmlspecialchars(isset($user_data['username']) ? $user_data['username'] : ''); ?>" required></div>
                    <div><label>Password</label><input type="password" placeholder="Password" name="password"  ></div>
                    <div>
                        <label>Role</label>
                        <select name="role" required>
                            <option value="">Select Role</option>
                            <option value="0" disabled <?php if (isset($user_data) && $user_data['role'] == 0) echo 'selected'; ?>>Admin</option>
                            <option value="1" <?php if (isset($user_data) && $user_data['role'] == 1) echo 'selected'; ?>>Manager</option>
                            <option value="9" <?php if (isset($user_data) && $user_data['role'] == 9) echo 'selected'; ?>>Viewer</option>
                            <option value="3" <?php if (isset($user_data) && $user_data['role'] == 3) echo 'selected'; ?>>SR</option>
                            <option value="4" <?php if (isset($user_data) && $user_data['role'] == 4) echo 'selected'; ?>>Store</option>
                        
                        </select>
                    </div>
                  
                    <div>
                        <label>Status</label>
                        <select name="status" required>
                            <option value="1" <?php if (isset($user_data) && $user_data['status'] == 1) echo 'selected'; ?>>Active</option>
                            <option value="0" <?php if (isset($user_data) && $user_data['status'] == 0) echo 'selected'; ?>>Inactive</option>
                        </select>
                    </div>
                </div>
                
                
                <div class="form-actions">
                    <?php if (isset($user_edit_id)) {
                        echo '<button type="submit" name="update_user" class="btn btn-yellow"><i class="fa-solid fa-edit"></i> Update User</button>';
                    } else {
                        echo '<button type="submit" name="add_user" class="btn btn-yellow"><i class="fa-solid fa-plus"></i> Add User</button>';
                    }

                    ?>
                </div>
                 
             


            </form>
        </div>

        

        <div class="glass-panel printable">
            <div style="display: flex; justify-content: space-between; margin-bottom: 15px;">
                <span class="section-title" style="margin:0;">All User</span>
                <button onclick="window.print()" class="btn btn-dark" style="padding: 5px 15px; font-size: 0.8rem;"><i class="fa-solid fa-print"></i></button>
            </div>
            
            <div class="table-responsive">
                <table class="table-simple">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>User Name</th>
                            <th>Company</th>
                            <th>Role</th>
                            <th>Status</th>
                            <th>Created At</th>
                      
                            <th style="text-align: right;">Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        $query = "SELECT * FROM users WHERE role != 0 AND company_id='{$_SESSION['company_id']}' ORDER BY id DESC";
                        $result = mysqli_query($conn, $query);

                        if (mysqli_num_rows($result) > 0) {
                            while ($row = mysqli_fetch_assoc($result)) {
                                echo "<tr><td>" . $row['id'] . "</td><td>" . $row['username'] . "</td><td>" . $row['company_id'] . "</td><td>" . $row['role'] .
                                 "</td><td>" . $row['status'] . " LL: ". $row['last_login'] . "</td><td>" . $row['created_at'] . "</td> <td  style='text-align: right;'>
                                <i class='fa-solid fa-pen' style='color:var(--warning); margin-right: 10px; cursor: pointer;' onclick=\"window.location.href='users.php?user_edit_id=" . $row['id'] . "'\"><i></i>
                                </td></tr>";
                            }
                        }
                        ?>
                    </tbody>
                </table>
            </div>
        </div>


                            


        

        

    </div>



<?php
include 'footer.php';
?>