<?php
include 'header.php';
?>

    <div class="print-header">
        <h1>EIS Report</h1>
        <p>Generated by: @<?php echo $_SESSION['username']; ?> | Date: <?php echo date("Y-m-d"); ?></p>
    </div>

    <div class="container">

        <div class="text-center" style="text-align: center; margin: 30px 0;">
            <h2 style="font-weight: 300; font-size: 2rem;">Welcome Back</h2>
            <p style="color: #666;">Manage your data with our modern, vibrant interface.</p>
        </div>

        

        

        

        

    </div>

   

<?php
include 'footer.php';
?>