<?php
include 'header.php';
?>
<?php
if ($_SERVER['REQUEST_METHOD'] == 'POST') {
   

    if (isset($_POST['add_route'])) {
        $route_name = $_POST['route_name'];
        $status = $_POST['status'];
        $company_id = $_SESSION['company_id'];
        $check_query = "SELECT id FROM routes WHERE route_name='$route_name' AND company_id='$company_id'";
        $check_result = mysqli_query($conn, $check_query);
        if (mysqli_num_rows($check_result) > 0) {
            echo "<script>alert('Route name already exists'); window.location.href='routes.php';</script>";
            exit();
        }

        $query = "INSERT INTO routes (route_name, status, company_id) VALUES ('$route_name', '$status', '$company_id')";
        mysqli_query($conn, $query);
        header("Location: routes.php");
        exit();
    }
    if (isset($_POST['update_route'])) {
        $route_id = $_GET['route_edit_id'];
        $route_name = $_POST['route_name'];
        $status = $_POST['status'];

        $check_query = "SELECT id FROM routes WHERE route_name='$route_name' AND id != '$route_id' AND company_id='{$_SESSION['company_id']}'";
        $check_result = mysqli_query($conn, $check_query);
        if (mysqli_num_rows($check_result) > 0) {
            echo "<script>alert('Route name already exists'); window.location.href='routes.php';</script>";
            exit();
        }

        $update_fields = "route_name='$route_name', status='$status'";

        $query = "UPDATE routes SET $update_fields WHERE id='$route_id'";
        mysqli_query($conn, $query);
        header("Location: routes.php");
        exit();
    }
    
}
      

?>
    <div class="print-header">
           <h1><?php echo APP_NAME; ?> Report</h1>
        <p>Generated by: <?php echo $_SESSION['user_id'] . "@".$_SESSION['username']. " | Company: " . $_SESSION['company_id']; ?> | Date: <?php echo date("Y-m-d"); ?></p>

    </div>

    <div class="container">

        <div class="text-center" style="text-align: center; margin: 30px 0;">
            <h2 style="font-weight: 300; font-size: 2rem;">Route List</h2>
            <p style="color: #666;">Create and manage routes.</p>
        </div>

        
        
        


        

        <div class="glass-panel form-section">
            <span class="section-title">New Route Add</span>
            <form method="POST">


                <?php if (isset($_GET['route_edit_id'])) {
                    $route_edit_id = $_GET['route_edit_id'];
                    $query = "SELECT * FROM routes WHERE id='$route_edit_id'";
                    $result = mysqli_query($conn, $query);
                    if (mysqli_num_rows($result) > 0) {
                        $route_data = mysqli_fetch_assoc($result);
                    }
                }
                ?>
                <div class="desktop-span-2">
                   <div class="grid-layout desktop-4" style="grid-template-columns: 1fr 1fr;">
                  
                    <div><label>Route Name</label><input type="text"  id="route_name" placeholder="Route Name" name="route_name" value="<?php echo htmlspecialchars(isset($route_data['route_name']) ? $route_data['route_name'] : ''); ?>"
                    pattern="[A-Z]+(?:\s[A-Z]+)?" required></div>

                    
                     <script>
                        // JavaScript function to validate Route Name input
                       

                    function validateName() {
                        const routeNameInput = document.getElementById('route_name');
                        const routeName = routeNameInput.value;
                        const pattern = /^[A-Z]+(?:\s[A-Z]+)?$/;

                        if (!pattern.test(routeName)) {
                            // If the input does not match the pattern, modify it
                            routeNameInput.value = routeName.toUpperCase().replace(/[^A-Z\s]/g, '').replace(/\s+/g, ' ').trim();
                        }
                    }
                     //onchange id = "route_name" calls this function
                     document.getElementById('route_name').addEventListener('change', validateName);
                </script>





                    <div><label>Status</label>


                    <select name="status">
                        <option value="1" <?php echo isset($route_data['status']) && $route_data['status'] == 1 ? 'selected' : ''; ?>>Active</option>
                        <option value="0" <?php echo isset($route_data['status']) && $route_data['status'] == 0 ? 'selected' : ''; ?>>Inactive</option>
                    </select>
                </div>
                    </div>
                </div>
                
                
                
                <div class="form-actions">
                    <?php if (isset($route_edit_id)) {
                        echo '<button type="submit" name="update_route" class="btn btn-yellow"><i class="fa-solid fa-edit"></i> Update Route</button>';
                    } else {
                        echo '<button type="submit" name="add_route" class="btn btn-yellow"><i class="fa-solid fa-plus"></i> Add Route</button>';
                    }

                    ?>
                </div>
                 
             


            </form>
        </div>

        

        <div class="glass-panel printable">
            <div style="display: flex; justify-content: space-between; margin-bottom: 15px;">
                <span class="section-title" style="margin:0;">All Routes</span>
                <button onclick="window.print()" class="btn btn-dark" style="padding: 5px 15px; font-size: 0.8rem;"><i class="fa-solid fa-print"></i></button>
            </div>
            
            <div class="table-responsive">
                <table class="table-simple">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Route Name</th>
                            <th>Status</th>
                           
                      
                            <th style="text-align: right;">Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        $query = "SELECT * FROM routes WHERE company_id='{$_SESSION['company_id']}' ORDER BY id DESC";
                        $result = mysqli_query($conn, $query);

                        if (mysqli_num_rows($result) > 0) {
                            while ($row = mysqli_fetch_assoc($result)) {
                              echo "
<tr>
    <td>{$row['id']}</td>
    <td>{$row['route_name']}</td>
    <td>" . 
        ($row['status'] 
            ? "<span class='badge bg-green'>Active</span>" 
            : "<span class='badge bg-red'>Inactive</span>") . 
    "</td>
    <td style='text-align: right;'>
        <i class='fa-solid fa-pen' 
           style='color: var(--warning); margin-right: 10px; cursor: pointer;' 
           onclick=\"window.location.href='routes.php?route_edit_id={$row['id']}'\">
        </i>
    </td>
</tr>";
                            }
                        }
                        ?>
                    </tbody>
                </table>
            </div>
        </div>


                            


        

        

    </div>



<?php
include 'footer.php';
?>