<?php
include 'header.php';
?>
<?php
if ($_SERVER['REQUEST_METHOD'] == 'POST') {
   

    if (isset($_POST['add_shop'])) {
        $shop_name = $_POST['shop_name'];
        $route_id = $_POST['route_id'];
        $user_id = $_SESSION['user_id'];
        $status = $_POST['status'];
        $company_id = $_SESSION['company_id'];
        $check_query = "SELECT id FROM shops WHERE shop_name='$shop_name'";
        $check_result = mysqli_query($conn, $check_query);
        if (mysqli_num_rows($check_result) > 0) {
            echo "<script>alert('Shop name already exists'); window.location.href='shops.php';</script>";
            exit();
        }

        $query = "INSERT INTO shops (shop_name, route_id, user_id, status, company_id) VALUES ('$shop_name', '$route_id', '$user_id', '$status', '$company_id')";
        mysqli_query($conn, $query);
        header("Location: shops.php");
        exit();
    }
    if (isset($_POST['update_shop'])) {
        $shop_id = $_GET['shop_edit_id'];
        $shop_name = $_POST['shop_name'];
        $status = $_POST['status'];

        $check_query = "SELECT id FROM shops WHERE shop_name='$shop_name' AND id != '$shop_id'";
        $check_result = mysqli_query($conn, $check_query);
        if (mysqli_num_rows($check_result) > 0) {
            echo "<script>alert('Shop name already exists'); window.location.href='shops.php';</script>";
            exit();
        }

        $update_fields = "shop_name='$shop_name', status='$status'";
        $query = "UPDATE shops SET $update_fields WHERE id='$shop_id'";
        mysqli_query($conn, $query);
        header("Location: shops.php");
        exit();
    }
    
}
      

?>
    <div class="print-header">
           <h1><?php echo APP_NAME; ?> Report</h1>
        <p>Generated by: <?php echo $_SESSION['user_id'] . "@".$_SESSION['username']. " | Company: " . $_SESSION['company_id']; ?> | Date: <?php echo date("Y-m-d"); ?></p>

    </div>

    <div class="container">

        <div class="text-center" style="text-align: center; margin: 30px 0;">
            <h2 style="font-weight: 300; font-size: 2rem;">Shop List</h2>
            <p style="color: #666;">Create and manage shops.</p>
        </div>

        
        
        


        

        <div class="glass-panel form-section">
            <span class="section-title">New Shop Add</span>
            <form method="POST">


                <?php if (isset($_GET['shop_edit_id'])) {
                    $shop_edit_id = $_GET['shop_edit_id'];
                    $query = "SELECT * FROM shops WHERE id='$shop_edit_id'";
                    $result = mysqli_query($conn, $query);
                    if (mysqli_num_rows($result) > 0) {
                        $shop_data = mysqli_fetch_assoc($result);
                    }
                }
                ?>
                <div class="desktop-span-2">
                    <div class="col-1">
                        <label>Shop Details</label>
              <input type="text"
       pattern="^[A-Z\s]+,\s[A-Z\s]+(?:,\s[A-Z\s]+)?\s\d{11}$"
       placeholder="SHOP NAME, ADDRESS, DISTRICT 01765236683 or SHOP NAME, ADDRESS 01765236683"
       id="shop_name"
       name="shop_name"
       value="<?php echo htmlspecialchars(isset($shop_data['shop_name']) ? $shop_data['shop_name'] : ''); ?>"
       required>

       <script>
    function validateName() {
    const input = document.getElementById('shop_name');
    let value = input.value;

    // Force uppercase, remove invalid chars
    value = value.toUpperCase()
                 .replace(/[^A-Z0-9,\s]/g, '')  // allow only A-Z, digits, commas, spaces
                 .replace(/\s+/g, ' ')          // normalize spaces
                 .trim();

    input.value = value;

    const pattern = /^[A-Z\s]+,\s[A-Z\s]+(?:,\s[A-Z\s]+)?\s\d{11}$/;
    if (!pattern.test(value)) {
        alert("Format must be: SHOP NAME, ADDRESS 017XXXXXXXXX or SHOP NAME, ADDRESS, DISTRICT 017XXXXXXXXX");
    }
}

document.getElementById('shop_name').addEventListener('change', validateName);
         </script>
                   
                    </div>
                   <div class="grid-layout desktop-4" style="grid-template-columns: 1fr 1fr;">
                  
                    <div><label>Route Name</label>

                    <select name="route_id" id="route_id" required>
                        <option value="">Select Route</option>
                        <?php
                            $query = "SELECT id, route_name FROM routes WHERE company_id='{$_SESSION['company_id']}' AND status=1 ORDER BY route_name ASC";
                            $result = mysqli_query($conn, $query);
                            if (mysqli_num_rows($result) > 0) {
                                while ($row = mysqli_fetch_assoc($result)) {
                                    $selected = (isset($shop_data['route_id']) && $shop_data['route_id'] == $row['id']) ? 'selected' : '';
                                    echo "<option value='" . $row['id'] . "' $selected>" . $row['route_name'] . "</option>";
                                }
                            }
                        ?>
                    </select>
                    <script>
                        $(document).ready(function() {
                            $('#route_id').select2({
                                placeholder: "Select Route",
                                allowClear: true
                            });
                        });
                    </script>
                    </div>
                    <div><label>Status</label>
                    <select name="status">
                        <option value="1" <?php echo isset($shop_data['status']) && $shop_data['status'] == 1 ? 'selected' : ''; ?>>Active</option>
                        <option value="0" <?php echo isset($shop_data['status']) && $shop_data['status'] == 0 ? 'selected' : ''; ?>>Inactive</option>
                    </select>
                </div>
                    </div>
                </div>
                
                
                
                <div class="form-actions">
                    <?php if (isset($shop_edit_id)) {
                        echo '<button type="submit" name="update_shop" class="btn btn-yellow"><i class="fa-solid fa-edit"></i> Update Shop</button>';
                    } else {
                        echo '<button type="submit" name="add_shop" class="btn btn-yellow"><i class="fa-solid fa-plus"></i> Add Shop</button>';
                    }

                    ?>
                </div>
                 
             


            </form>
        </div>

        

        <div class="glass-panel printable">
            <div style="display: flex; justify-content: space-between; margin-bottom: 15px;">
                <span class="section-title" style="margin:0;">All Shops</span>
                <button onclick="window.print()" class="btn btn-dark" style="padding: 5px 15px; font-size: 0.8rem;"><i class="fa-solid fa-print"></i></button>
            </div>
            
            <div class="table-responsive">
                <table class="table-simple">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Shop Name</th>
                            <th>Route Name</th>
                            <th>Balance</th>
                            <th>Status</th>
                           
                      
                            <th style="text-align: right;">Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        $company_id = $_SESSION['company_id'];
                        $query = "SELECT * FROM shops WHERE company_id='$company_id' ORDER BY id DESC";
                        $result = mysqli_query($conn, $query);

                        if (mysqli_num_rows($result) > 0) {
                            while ($row = mysqli_fetch_assoc($result)) {
                                $route_name_query = "SELECT route_name FROM routes WHERE id='{$row['route_id']}'";
                                $route_name_result = mysqli_query($conn, $route_name_query);
                                $route_name = mysqli_fetch_assoc($route_name_result)['route_name'];
                              echo "
<tr>
    <td>{$row['id']}</td>
    <td>{$row['shop_name']}</td>
    <td>{$route_name}</td>
    <td>{$row['balance']}</td>
  
    <td>" . 
        ($row['status'] 
            ? "<span class='badge bg-green'>Active</span>" 
            : "<span class='badge bg-red'>Inactive</span>") . 
    "</td>
    <td style='text-align: right;'>
        <i class='fa-solid fa-pen' 
           style='color: var(--warning); margin-right: 10px; cursor: pointer;' 
           onclick=\"window.location.href='shops.php?shop_edit_id={$row['id']}'\">
        </i>
    </td>
</tr>";
                            }
                        }
                        ?>
                    </tbody>
                </table>
            </div>
        </div>


                            


        

        

    </div>



<?php
include 'footer.php';
?>