<?php
include 'header.php';
?>

    <div class="print-header">
           <h1><?php echo APP_NAME; ?> Report</h1>
        <p>Generated by: <?php echo $_SESSION['user_id'] . "@".$_SESSION['username']. " | Company: " . $_SESSION['company_id']; ?> | Date: <?php echo date("Y-m-d"); ?></p>

    </div>

    <div class="container">

        <div class="text-center" style="text-align: center; margin: 30px 0;">
            <h2 style="font-weight: 300; font-size: 2rem;">Welcome Back Viewer</h2>
            <p style="color: #666;">View your Company data.</p>
        </div>

        
    </div>
<?php
include 'footer.php';
?>