<?php
include 'header.php';

// Function to get address from lat/lng using Nominatim (OpenStreetMap)
function getAddressFromLatLng($lat, $lng) {
    if ($lat == 0 && $lng == 0) {
        return "No data";
    }
    $url = "https://nominatim.openstreetmap.org/reverse?format=json&lat=$lat&lon=$lng";

    // Nominatim requires a User-Agent header
    $opts = [
        "http" => [
            "header" => "User-Agent: MySchoolApp/1.0\r\n"
        ]
    ];
    $context = stream_context_create($opts);

    $response = @file_get_contents($url, false, $context);
    if ($response === FALSE) {
        return "$lat, $lng"; // fallback if API fails
    }

    $json = json_decode($response, true);
    return $json['display_name'] ?? "$lat, $lng";
}
?>

<div class="print-header">
    <h1><?php echo APP_NAME; ?> Location Report</h1>
    <p>
        Generated by: <?php echo $_SESSION['user_id'] . "@" . $_SESSION['username'] . " | Company: " . $_SESSION['company_id']; ?> 
        | Date: <?php echo date("Y-m-d"); ?>
    </p>
</div>

<div class="container">
   
<div class=" form-section" style="margin-bottom: 20px;">
          
            <form method="GET">


                <?php if (isset($_GET['order_edit_id'])) {
                    $order_edit_id = $_GET['order_edit_id'];
                    $query = "SELECT * FROM orders WHERE id='$order_edit_id'";
                    $result = mysqli_query($conn, $query);
                    if (mysqli_num_rows($result) > 0) {
                        $order_data = mysqli_fetch_assoc($result);
                    }
                }
                ?>
                <div class="desktop-span-2">
                   


                   
                    
                <div class="grid-layout desktop-4" style="grid-template-columns: 1fr 1fr;">
                    <div><label>Date From</label>
                    <input type="date" placeholder="Date" name="date_from" value="<?php echo isset($_GET['date_from']) ? $_GET['date_from'] : date('Y-m-d'); ?>" required>
                    </div>
                    <div><label>Date To</label>
                    <input type="date" placeholder="Date" name="date_to" value="<?php echo isset($_GET['date_to']) ? $_GET['date_to'] : date('Y-m-d'); ?>" required>
                    </div>
                    <div><label>Route Name</label>
                        
                        <select name="search_route_id" >
                            <option value="">All Route</option>
                            <?php
                            $query = "SELECT id, route_name FROM routes WHERE status = 1 ORDER BY id DESC";
                            $result = mysqli_query($conn, $query);
                            if (mysqli_num_rows($result) > 0) {
                                while ($row = mysqli_fetch_assoc($result)) {
                                    $selected = (isset($_GET['search_route_id']) && $_GET['search_route_id'] == $row['id']) ? 'selected' : '';
                                    echo "<option value='" . $row['id'] . "' $selected>" . $row['route_name'] . "</option>";
                                }
                            }
                            ?>
                        </select>
                    </div>
                    <div>
                                                                    
                        
                        <label>Shop Name</label>
                        <select name="search_shop_id" >
                            <option value="">All Shop</option>
                            <?php
                            $query = "SELECT id, shop_name FROM shops WHERE status = 1 ORDER BY id DESC";
                            $result = mysqli_query($conn, $query);
                            if (mysqli_num_rows($result) > 0) {
                                while ($row = mysqli_fetch_assoc($result)) {
                                    $selected = (isset($_GET['search_shop_id']) && $_GET['search_shop_id'] == $row['id']) ? 'selected' : '';
                                    echo '<option value="' . $row['id'] . '" ' . $selected . '>' . $row['shop_name'] . '</option>';
                                }
                            }
                            ?>
                        </select>
                    </div>
            

                  
                    <div><label>User</label>
                    <select name="search_id">
                        <option value="">All</option>
                        <?php
                            $query = "SELECT id, username FROM users WHERE status = 1 AND role IN (1, 3) ORDER BY id DESC";
                            $result = mysqli_query($conn, $query);
                            if (mysqli_num_rows($result) > 0) {
                                while ($row = mysqli_fetch_assoc($result)) {
                                    $selected = (isset($_GET['search_id']) && $_GET['search_id'] == $row['id']) ? 'selected' : '';
                                    echo '<option value="' . $row['id'] . '" ' . $selected . '>' . $row['username'] . '</option>';
                                }
                            }
                        ?>
                    </select>
                    </div>
                    <div><label>Status</label>
                    <select name="search_status">
                  
                        
                        <option value="4" <?php echo isset($_GET['search_status']) && $_GET['search_status'] == 4 ? 'selected' : ''; ?>>Confirmed</option>
                        <option value="3" <?php echo isset($_GET['search_status']) && $_GET['search_status'] == 3 ? 'selected' : ''; ?>>Draft</option>

                    </select>
                </div>
                    </div>
                </div>
                
                
                
                <div class="form-actions">
                   <button type="submit" name="search_order" class="btn btn-green"><i class="fa-solid fa-search"></i> Search</button>
                </div>
                 
             
 

            </form>
        </div>
    <div class="glass-panel printable">
        <div style="display: flex; justify-content: space-between; margin-bottom: 15px;">
            <span class="section-title" style="margin:0;">All User's Location</span>
            <button onclick="window.print()" class="btn btn-dark" style="padding: 5px 15px; font-size: 0.8rem;">
                <i class="fa-solid fa-print"></i>
            </button>
        </div>
        
        <div class="table-responsive">
            <table class="table-simple" id="dataTable">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th style='display: none'>lat</th>
                        <th style='display: none'>long</th>
                        <th>User</th>
                        <th>Order</th>
                        <th>Location</th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    if (isset($_GET['search_order'])) {
                        $query = "SELECT * FROM orders WHERE 1=1 ";
                        if (isset($_GET['search_id']) && !empty($_GET['search_id'])) {
                            $query .= " AND created_by='" . $_GET['search_id'] . "'";
                        }
                        if (isset($_GET['search_route_id']) && !empty($_GET['search_route_id'])) {
                            $query .= " AND route_id='" . $_GET['search_route_id'] . "'";
                        }
                        if (isset($_GET['search_shop_id']) && !empty($_GET['search_shop_id'])) {
                            $query .= " AND shop_id='" . $_GET['search_shop_id'] . "'";
                        }
                        if (isset($_GET['search_status']) && !empty($_GET['search_status'])) {
                            if ($_GET['search_status'] == 3) {
                                $query .= " AND order_status=0";
                            } else if ($_GET['search_status'] == 4) {
                                $query .= " AND order_status=1";
                            }

                           
                        }
                        if (isset($_GET['date_from']) && !empty($_GET['date_from']) && isset($_GET['date_to']) && !empty($_GET['date_to'])) {
                            $from_date = $_GET['date_from'] . " 00:00:00";
                            $to_date = $_GET['date_to'] . " 23:59:59";
                            $query .= " AND created_at BETWEEN '" . $from_date . "' AND '" . $to_date . "'";
                        }
                        $query .= " ORDER BY id DESC";
                    } else {
                        $query = "SELECT * FROM orders WHERE order_status=1 ORDER BY id DESC LIMIT 5";
                    }
                        $result = mysqli_query($conn, $query);
                    if (mysqli_num_rows($result) > 0) {
                        while ($row = mysqli_fetch_assoc($result)) {

                            // get company name
                            $company_query = "SELECT name FROM companies WHERE id='" . $row['company_id'] . "'";
                            $company_result = mysqli_query($conn, $company_query);
                            $company_row = mysqli_fetch_assoc($company_result);
                            $company_name = $company_row['name'];

                            // get user name
                            $username = $row['created_by'];
                            $user_name_query = "SELECT username FROM users WHERE id='" . $username . "'";
                            $user_name_result = mysqli_query($conn, $user_name_query);
                            $user_name_row = mysqli_fetch_assoc($user_name_result);
                            $user_name = $user_name_row['username'];
                            //route name
                            $route_name_query = "SELECT route_name FROM routes WHERE id='" . $row['route_id'] . "'";
                            $route_name_result = mysqli_query($conn, $route_name_query);
                            $route_name_row = mysqli_fetch_assoc($route_name_result);
                            $route_name = $route_name_row['route_name'];
                            //shop name
                            $shop_name_query = "SELECT shop_name FROM shops WHERE id='" . $row['shop_id'] . "'";
                            $shop_name_result = mysqli_query($conn, $shop_name_query);
                            $shop_name_row = mysqli_fetch_assoc($shop_name_result);
                            $shop_name = $shop_name_row['shop_name'];

                            //get all the orders from oder_items table
                            $order_items_query = "SELECT * FROM order_items WHERE order_id='" . $row['id'] . "'";
                            $order_items_result = mysqli_query($conn, $order_items_query);
                            $order_items = mysqli_fetch_all($order_items_result, MYSQLI_ASSOC);

                            $total_quantity = 0;
                            $total_price = 0;
                            $items_text="";
                            foreach ($order_items as $order_item) {
                                $total_quantity += $order_item['quantity'];
                                $total_price += $order_item['price'] * $order_item['quantity'];
                                $item_name_query = "SELECT item_name FROM items WHERE id='" . $order_item['item_id'] . "'";
                                $item_name_result = mysqli_query($conn, $item_name_query);
                                $item_name_row = mysqli_fetch_assoc($item_name_result);
                                $order_item['item_name'] = $item_name_row['item_name'];
                                $items_text .= $order_item['item_name'] . " (" . $order_item['price'] . " x " . $order_item['quantity'] . "= $" . $order_item['price'] * $order_item['quantity'] . "), ";
                            }
                            $orders_info = "Items: " . count($order_items) . ", Qty: " . $total_quantity . ", Total: $" . number_format($total_price, 2);
                            $order_items_info = nl2br($orders_info);

                            // get address from lat/lng
                          //  $address = getAddressFromLatLng($row['latitude'], $row['longitude']);

                            echo "<tr>
                                    <td>" . $row['id'] ."<br>" . $user_name . " @ " . $row['created_at'].  "</td>
                                    <td style='display: none'>" . $row ['latitude'] .  "</td>
                                    <td style='display: none'>" . $row['longitude'] . "</td>
                                    <td>Order #" . $row['id'] . " - " . $company_name  . " [" . ($row['order_status'] ? "Confirmed" : "Pending") . "]<br>" . $route_name . " - " . $shop_name . "</td>
                                    <td>" . $items_text . "<br>" . $order_items_info . "</td>
                                    <td> <span id='address_" . $row['id'] . "'></span>
                                    <button id='btn_" . $row['id'] . "' onClick=\"getLocation('" . $row['latitude'] . "', '" . $row['longitude'] . "', " . $row['id'] . ")\">👁️</button></td>
                                  </tr>";
                        }
                    }
                    ?>
                </tbody>

               <script>
function getLocation(lat, lng, orderId) {
    if (lat == 0 && lng == 0) {
        console.log("No data for order " + orderId);
        document.getElementById("address_" + orderId).innerText = "No data";
        document.getElementById("btn_" + orderId).style.display = "none";
        return;
    }

    console.log(`Getting address for order ${orderId} with lat=${lat} and lng=${lng}`);

    const button = document.getElementById("btn_" + orderId);
    button.style.display = "none";

    const addressElement = document.getElementById("address_" + orderId);
    addressElement.innerHTML = '<div class="spinner-border text-primary" role="status"><span class="visually-hidden">Loading...</span></div>';

    // Direct request to BigDataCloud
    fetch(`https://api.bigdatacloud.net/data/reverse-geocode-client?latitude=${lat}&longitude=${lng}&localityLanguage=en`)
        .then(res => res.json())
        .then(data => {
            // BigDataCloud fields
            const locality = data.locality || "";
            const city = data.city || ""; // sometimes present
            const subdivision = data.principalSubdivision || "";
            const country = data.countryName || "";

            const addressText = [locality, city, subdivision, country]
                .filter(Boolean)
                .join(', ');

            console.log(`Address for order ${orderId}: ${addressText}`);
            addressElement.innerText = addressText || "No data";
        })
        .catch(err => {
            console.error(`Error getting address for order ${orderId}: ${err.message}`);
            addressElement.innerText = "No data";
        });
}
</script>
            </table>
        </div>
    </div>


<!-- Leaflet CSS -->
<link rel="stylesheet" href="https://unpkg.com/leaflet/dist/leaflet.css" />

<!-- Leaflet JS -->
<script src="https://unpkg.com/leaflet/dist/leaflet.js"></script>

<div class="glass-panel printable">
<div style="text-align:center; margin:20px;">
  <button id="showMapBtn" style="padding:10px 20px; font-size:16px; cursor:pointer;">
    Show Map
  </button>
</div>
<div id ="mapTitle" style="text-align:center; font-size:20px; font-weight:bold; margin:10px; display:none">
  Order Tracking Map (Bangladesh)
</div>

<div id="map" style="height:900px; width:100%; margin-bottom:20px; display:none"></div>
</div>
<script>
document.getElementById("showMapBtn").addEventListener("click", () => {
    document.getElementById("map").style.display = "block";
    document.getElementById("mapTitle").style.display = "block";
    document.getElementById("showMapBtn").style.display = "none";
    showMap();
});

function showMap() {
    // Center map on Bangladesh
    const map = L.map('map').setView([23.685, 90.3563], 7);

    L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
        attribution: '&copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors',
        subdomains: ['a', 'b', 'c']
    }).addTo(map);

    const colorPalette = ["red","blue","green","orange","purple","brown","teal","magenta"];
    const userColors = {};
    const markers = [];
    const orders = [];

    const table = document.getElementById("dataTable");
    const rows = table.getElementsByTagName("tr");

    for (let i = 0; i < rows.length; i++) {
        const cells = rows[i].getElementsByTagName("td");
        if (cells.length >= 3) {
            const meta = cells[0].innerText.trim(); // e.g. "17 a @ 2025-12-19 00:46:06"
            const lat = parseFloat(cells[1].innerText);
            const lng = parseFloat(cells[2].innerText);

            if (!isNaN(lat) && !isNaN(lng) && lat !== 0 && lng !== 0 &&
                lat >= -90 && lat <= 90 && lng >= -180 && lng <= 180) {

                // Robust parsing
                const parts = meta.split("@");
                const leftPart = parts[0].trim();   // "17 a"
                const timeStr = parts[1] ? parts[1].trim() : "";
                const [orderIdStr, userName] = leftPart.split(/\s+/);
                const orderId = parseInt(orderIdStr, 10);
                const orderTime = new Date(timeStr);

                // Assign consistent color per user
                if (!userColors[userName]) {
                    const assignedColor = colorPalette[Object.keys(userColors).length % colorPalette.length];
                    userColors[userName] = assignedColor;
                }
                const color = userColors[userName];

                orders.push({ orderId, user:userName, lat, lng, time:orderTime, color });
            }
        }
    }

    // Sort by time
    orders.sort((a,b) => a.time - b.time);

    // Animate markers with 1s delay
    let idx = 0;
    function showNextOrder() {
        if (idx >= orders.length) return;
        const order = orders[idx];

        const marker = L.circleMarker([order.lat, order.lng], {
            radius: 10,
            color: order.color,
            fillColor: order.color,
            fillOpacity: 0.8
        }).addTo(map);

        marker.bindPopup(
            `<b>Order #${order.orderId}</b><br>User: ${order.user}<br>Time: ${order.time}<br>Lat: ${order.lat}, Lng: ${order.lng}`
        );
        // Permanent label with username
        marker.bindTooltip(order.user, { permanent:true, direction:"top", offset:[0,-10] });

        markers.push(marker);
        idx++;
        setTimeout(showNextOrder, 1000); // 1 second delay
    }

    showNextOrder();
}
</script>


</div>

<?php
include 'footer.php';
?>