<?php
include 'header.php';
?>

    <div class="print-header">
           <h1><?php echo APP_NAME; ?> Report</h1>
        <p>Generated by: <?php echo $_SESSION['user_id'] . "@".$_SESSION['username']. " | Company: " . $_SESSION['company_id']; ?> | Date: <?php echo date("Y-m-d"); ?></p>

    </div>

    <div class="container">

        <div class="text-center" style="text-align: center; margin: 30px 0;">
            <h2 style="font-weight: 300; font-size: 2rem;">Welcome Back Viewer</h2>
            <p style="color: #666;">View your Company data.</p>
        </div>

         <div class="glass-panel printable">
            <div style="display: flex; justify-content: space-between; margin-bottom: 15px;">
                <span class="section-title" style="margin:0;">All User</span>
                <button onclick="window.print()" class="btn btn-dark" style="padding: 5px 15px; font-size: 0.8rem;"><i class="fa-solid fa-print"></i></button>
            </div>
            
            <div class="table-responsive">
                <table class="table-simple">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>User Name</th>
                            <th>Company</th>
                            <th>Role</th>
                            <th>Status</th>
                            <th>Created At</th>
                            <th>Last Login</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        $query = "SELECT * FROM users ORDER BY last_login DESC";
                        $result = mysqli_query($conn, $query);
                        if (mysqli_num_rows($result) > 0) {
                            while ($row = mysqli_fetch_assoc($result)) {

                                //get company name
                                $company_query = "SELECT name FROM companies WHERE id='" . $row['company_id'] . "'";
                                $company_result = mysqli_query($conn, $company_query);
                                $company_row = mysqli_fetch_assoc($company_result);
                                $company_name = $company_row['name'];
                                echo "<tr><td>" . $row['id'] . "</td><td>" . $row['username'] . "</td><td>" . $company_name . "</td><td>" . $row['role'] .
                                 "</td><td>" . $row['status'] . "</td><td>" . $row['created_at'] . "</td><td>" . $row['last_login'] ."</tr>";
                            }
                        }
                        ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
<?php
include 'footer.php';
?>