<?php
include 'header.php';
?>
<?php
if ($_SERVER['REQUEST_METHOD'] == 'POST') {
   

    if (isset($_POST['add_survey'])) {
        $survey_name = $_POST['survey_name'];
        $survey_type = $_POST['survey_type'];
        $survey_address = $_POST['survey_address'];
        $survey_phone = $_POST['survey_phone'];
        $route_id = $_POST['route_id'];
        $user_id = $_SESSION['user_id'];
        $status = $_POST['status'];
        $company_id = $_SESSION['company_id'];
        $check_query = "SELECT id FROM surveys WHERE survey_name='$survey_name' AND survey_type='$survey_type' AND survey_address='$survey_address' AND survey_phone='$survey_phone' AND company_id='$company_id'";
        $check_result = mysqli_query($conn, $check_query);
        if (mysqli_num_rows($check_result) > 0) {
            echo "<script>alert('survey name already exists'); window.location.href='survey.php';</script>";
            exit();
        }

        $query = "INSERT INTO surveys (survey_name, route_id, user_id, status, company_id, survey_type, survey_address, survey_phone) VALUES ('$survey_name', '$route_id', '$user_id', '$status', '$company_id', '$survey_type', '$survey_address', '$survey_phone')";
        mysqli_query($conn, $query);
        header("Location: survey.php");
        exit();
    }
    if (isset($_POST['update_survey'])) {
        $survey_id = $_GET['survey_edit_id'];
        $survey_name = $_POST['survey_name'];
        $survey_type = $_POST['survey_type'];
        $survey_address = $_POST['survey_address'];
        $survey_phone = $_POST['survey_phone'];
        $status = $_POST['status'];
        $company_id = $_SESSION['company_id'];


        $check_query = "SELECT id FROM surveys WHERE survey_name='$survey_name' AND survey_type='$survey_type' AND survey_address='$survey_address' AND survey_phone='$survey_phone' AND id != '$survey_id' AND company_id='{$_SESSION['company_id']}'";
        $check_result = mysqli_query($conn, $check_query);
        if (mysqli_num_rows($check_result) > 0) {
            echo "<script>alert('survey name already exists'); window.location.href='survey.php';</script>";
            exit();
        }

        $update_fields = "survey_name='$survey_name', survey_type='$survey_type', survey_address='$survey_address', survey_phone='$survey_phone', status='$status'";
        $query = "UPDATE surveys SET $update_fields WHERE id='$survey_id'";
        mysqli_query($conn, $query);
        header("Location: survey.php");
        exit();
    }
    
}
      

?>
    <div class="print-header">
           <h1><?php echo APP_NAME; ?> Report</h1>
        <p>Generated by: <?php echo $_SESSION['user_id'] . "@".$_SESSION['username']. " | Company: " . $_SESSION['company_id']; ?> | Date: <?php echo date("Y-m-d"); ?></p>

    </div>

    <div class="container">

        <div class="text-center" style="text-align: center; margin: 30px 0;">
            <h2 style="font-weight: 300; font-size: 2rem;">survey List</h2>
            <p style="color: #666;">Create and manage surveys.</p>
        </div>

        
        
        


        

        <div class="glass-panel form-section">
            <span class="section-title">New survey Add</span>
            <form method="POST">


                <?php if (isset($_GET['survey_edit_id'])) {
                    $survey_edit_id = $_GET['survey_edit_id'];
                    $query = "SELECT * FROM surveys WHERE id='$survey_edit_id'";
                    $result = mysqli_query($conn, $query);
                    if (mysqli_num_rows($result) > 0) {
                        $survey_data = mysqli_fetch_assoc($result);
                    }
                }
                ?>
                <div class="desktop-span-2">
                    
                   <div class="grid-layout desktop-4" style="grid-template-columns: 1fr 1fr;">
                  
                    <div><label>Route Name</label>

                    <select name="route_id" id="route_id" required>
                        <option value="">Select Route</option>
                        <?php
                            $query = "SELECT id, route_name FROM routes WHERE company_id='{$_SESSION['company_id']}' AND status=1 ORDER BY route_name ASC";
                            $result = mysqli_query($conn, $query);
                            if (mysqli_num_rows($result) > 0) {
                                while ($row = mysqli_fetch_assoc($result)) {
                                    $selected = (isset($survey_data['route_id']) && $survey_data['route_id'] == $row['id']) ? 'selected' : '';
                                    echo "<option value='" . $row['id'] . "' $selected>" . $row['route_name'] . "</option>";
                                }
                            }
                        ?>
                    </select>
                    <script>
                        $(document).ready(function() {
                            $('#route_id').select2({
                                placeholder: "Select Route",
                                allowClear: true
                            });
                        });
                    </script>
                    </div>
                    <div><label>Status</label>
                    <select name="status">
                        <option value="1" <?php echo isset($survey_data['status']) && $survey_data['status'] == 1 ? 'selected' : ''; ?>>Active</option>
                        <option value="0" <?php echo isset($survey_data['status']) && $survey_data['status'] == 0 ? 'selected' : ''; ?>>Inactive</option>
                    </select>
                </div>

                <div><label>Survey Type</label>
                        <input type="text" name="survey_type" value="<?php echo isset($survey_data['survey_type']) ? $survey_data['survey_type'] : ''; ?>" required>
                </div>
                <div><label>Survey Name</label>
                        <input type="text" name="survey_name" value="<?php echo isset($survey_data['survey_name']) ? $survey_data['survey_name'] : ''; ?>" required>
                </div>
                <div><label>Survey Address</label>
                        <input type="text" name="survey_address" value="<?php echo isset($survey_data['survey_address']) ? $survey_data['survey_address'] : ''; ?>" required>
                </div>
                <div><label>Survey Phone</label>
                        <input type="text" name="survey_phone" value="<?php echo isset($survey_data['survey_phone']) ? $survey_data['survey_phone'] : ''; ?>" required>
                </div>
                    </div>
                </div>
                
                
                
                <div class="form-actions">
                    <?php if (isset($survey_edit_id)) {
                        echo '<button type="submit" name="update_survey" class="btn btn-yellow"><i class="fa-solid fa-edit"></i> Update survey</button>';
                    } else {
                        echo '<button type="submit" name="add_survey" class="btn btn-yellow"><i class="fa-solid fa-plus"></i> Add survey</button>';
                    }

                    ?>
                </div>
                 
             


            </form>
        </div>

        

        <div class="glass-panel printable">
            <div style="display: flex; justify-content: space-between; margin-bottom: 15px;">
                <span class="section-title" style="margin:0;">All surveys</span>
                <button onclick="window.print()" class="btn btn-dark" style="padding: 5px 15px; font-size: 0.8rem;"><i class="fa-solid fa-print"></i></button>
            </div>
            
            <div class="table-responsive">
                <table class="table-simple">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Type</th>
                            <th>survey Name</th>
                            <th>Address</th>
                            <th>Phone</th>
                            <th>Route Name</th>
                      
                            <th>Status</th>
                           
                      
                            <th style="text-align: right;">Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        $company_id = $_SESSION['company_id'];
                        $query = "SELECT * FROM surveys WHERE company_id='$company_id' ORDER BY id DESC";
                        $result = mysqli_query($conn, $query);

                        if (mysqli_num_rows($result) > 0) {
                            while ($row = mysqli_fetch_assoc($result)) {
                                $route_name_query = "SELECT route_name FROM routes WHERE id='{$row['route_id']}'";
                                $route_name_result = mysqli_query($conn, $route_name_query);
                                $route_name = mysqli_fetch_assoc($route_name_result)['route_name'];
                              echo "
<tr>
    <td>{$row['id']}</td>
    <td>{$row['survey_type']}</td>

    <td>{$row['survey_name']}</td>
        <td>{$row['survey_address']}</td>
    <td>{$row['survey_phone']}</td>
        <td>{$route_name}</td>
    <td>" . 
        ($row['status'] 
            ? "<span class='badge bg-green'>Active</span>" 
            : "<span class='badge bg-red'>Inactive</span>") . 
    "</td>
    <td style='text-align: right;'>
        <i class='fa-solid fa-pen' 
           style='color: var(--warning); margin-right: 10px; cursor: pointer;' 
           onclick=\"window.location.href='survey.php?survey_edit_id={$row['id']}'\">
        </i>
    </td>
</tr>";
                            }
                        }
                        ?>
                    </tbody>
                </table>
            </div>
        </div>


                            


        

        

    </div>



<?php
include 'footer.php';
?>