<?php
include 'header.php';
?>

    <div class="print-header">
           <h1><?php echo APP_NAME; ?> Report</h1>
        <p>Generated by: <?php echo $_SESSION['user_id'] . "@".$_SESSION['username']. " | Company: " . $_SESSION['company_id']; ?> | Date: <?php echo date("Y-m-d"); ?></p>

    </div>

    <div class="container">

        <div class="text-center" style="text-align: center; margin: 30px 0;">
            <h2 style="font-weight: 300; font-size: 2rem;">Welcome Back</h2>
            <p style="color: #666;">Manage your data with our modern, vibrant interface.</p>
        </div>

        

        

        

        <div class="glass-panel printable">
            <div style="display: flex; justify-content: space-between; margin-bottom: 15px;">
                <span class="section-title" style="margin:0;">Recent Orders</span>
                <button onclick="window.print()" class="btn btn-dark" style="padding: 5px 15px; font-size: 0.8rem;"><i class="fa-solid fa-print"></i></button>
            </div>
            
            <div class="table-responsive">
                <table class="table-simple">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Route</th>
                            <th>Shop</th>
                            <th>Total</th>
                            <th>Order</th>
                            <th>Delivery</th>
                            <th>Status</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        $query = "SELECT id, route_id, shop_id, total, order_date, delivery_date, status FROM orders";
                        $result = mysqli_query($conn, $query);

                        if (mysqli_num_rows($result) > 0) {
                            while($row = mysqli_fetch_assoc($result)) {
                        ?>
                        <tr>
                            <td><?php echo $row['id']; ?></td>
                            <td><?php echo $row['route']; ?></td>
                            <td><?php echo $row['shop']; ?></td>
                            <td><?php echo $row['price']; ?></td>
                            <td><?php echo date('Y-m-d', strtotime($row['order_date'])); ?></td>
                            <td><?php echo date('Y-m-d', strtotime($row['delivery_date'])); ?></td>
                            <td><span class="badge bg-<?php echo ($row['status'] == 'Completed' ? 'green' : ($row['status'] == 'Processing' ? 'yellow' : 'red')); ?>"><?php echo $row['status']; ?></span></td>
                        </tr>
                        <?php
                            }
                        }
                        ?>
         
                    </tbody>
                </table>
            </div>
        </div>

        <div class="glass-panel printable">
            <span class="section-title">Project Details</span>
            <div class="table-responsive">
                <table>
                    <thead>
                        <tr>
                            <th style="width: 40px;"></th>
                            <th>Project</th>
                            <th>Team Lead</th>
                            <th>Deadline</th>
                            <th style="text-align: right;">Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td><i class="fa-solid fa-circle-chevron-right toggle-icon" onclick="toggleRow(this)"></i></td>
                            <td><b>Website Redesign</b></td>
                            <td>Amy Winehouse</td>
                            <td>Oct 30, 2025</td>
                            <td style="text-align: right;">
                                <i class="fa-solid fa-pen" style="color:var(--warning); margin-right: 10px; cursor: pointer;"></i>
                                <i class="fa-solid fa-trash" style="color:var(--danger); cursor: pointer;"></i>
                            </td>
                        </tr>
                        <tr class="sub-row">
                            <td colspan="5" class="sub-cell">
                                <table style="width: 100%; font-size: 0.9rem; background: white; border-radius: 8px;">
                                    <tr style="background: #eee;"><th>Task</th><th>Status</th></tr>
                                    <tr><td>Wireframing</td><td style="color:var(--primary)">Done</td></tr>
                                    <tr><td>Frontend Coding</td><td style="color:var(--warning)">In Progress</td></tr>
                                </table>
                            </td>
                        </tr>

                        <tr>
                            <td><i class="fa-solid fa-circle-chevron-right toggle-icon" onclick="toggleRow(this)"></i></td>
                            <td><b>Mobile App</b></td>
                            <td>Kurt Cobain</td>
                            <td>Nov 15, 2025</td>
                            <td style="text-align: right;">
                                <i class="fa-solid fa-pen" style="color:var(--warning); margin-right: 10px; cursor: pointer;"></i>
                                <i class="fa-solid fa-trash" style="color:var(--danger); cursor: pointer;"></i>
                            </td>
                        </tr>
                        <tr class="sub-row">
                            <td colspan="5" class="sub-cell">
                                <p>No sub-tasks available.</p>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>

    </div>

   

<?php
include 'footer.php';
?>